services:
  db:
    image: postgres
    restart: always
    shm_size: 512mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/catbot/data

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#  cats-service:
#    build:
#      context: .
#      dockerfile: ./CatsService/Dockerfile
#    container_name: cats-service
#    environment:
#      - SPRING_DATASOURCE_URL = ${DB_URL}
#      - SPRING_KAFKA_BOOTSTRAP_SERVERS = ${KAFKA_BASE}
#    depends_on:
#      - kafka
#      - db
#
#  telegram-connector:
#    build:
#      context: .
#      dockerfile: ./TelegramConnector/Dockerfile
#    container_name: telegram-connector
#    environment:
#      - BOT_TOKEN = ${BOT_TOKEN}
#      - BOT_NAME = ${BOT_NAME}
#      - SPRING_DATASOURCE_URL = ${DB_URL}
#      - SPRING_KAFKA_BOOTSTRAP_SERVERS = ${KAFKA_BASE}
#    depends_on:
#      - kafka
#      - db

volumes:
  postgres_data: